/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule AppFeedQuery.graphql
 * @generated SignedSource<<db36f39e027e97c23cc16d6f6b2629a2>>
 * @relayHash b7c59720364cb32ea8be194add3adc2d
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query AppFeedQuery {
  feed(type: TOP, limit: 5) {
    repository {
      owner {
        login
      }
      name
      stargazers_count
    }
    postedBy {
      login
    }
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "AppFeedQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Literal",
            "name": "limit",
            "value": 5,
            "type": "Int"
          },
          {
            "kind": "Literal",
            "name": "type",
            "value": "TOP",
            "type": "FeedType!"
          }
        ],
        "concreteType": "Entry",
        "name": "feed",
        "plural": true,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "Repository",
            "name": "repository",
            "plural": false,
            "selections": [
              {
                "kind": "LinkedField",
                "alias": null,
                "args": null,
                "concreteType": "User",
                "name": "owner",
                "plural": false,
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "login",
                    "storageKey": null
                  }
                ],
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "name",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "stargazers_count",
                "storageKey": null
              }
            ],
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "User",
            "name": "postedBy",
            "plural": false,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "login",
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": "feed{\"limit\":5,\"type\":\"TOP\"}"
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "AppFeedQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "AppFeedQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Literal",
            "name": "limit",
            "value": 5,
            "type": "Int"
          },
          {
            "kind": "Literal",
            "name": "type",
            "value": "TOP",
            "type": "FeedType!"
          }
        ],
        "concreteType": "Entry",
        "name": "feed",
        "plural": true,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "Repository",
            "name": "repository",
            "plural": false,
            "selections": [
              {
                "kind": "LinkedField",
                "alias": null,
                "args": null,
                "concreteType": "User",
                "name": "owner",
                "plural": false,
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "login",
                    "storageKey": null
                  }
                ],
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "name",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "stargazers_count",
                "storageKey": null
              }
            ],
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "User",
            "name": "postedBy",
            "plural": false,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "login",
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": "feed{\"limit\":5,\"type\":\"TOP\"}"
      }
    ]
  },
  "text": "query AppFeedQuery {\n  feed(type: TOP, limit: 5) {\n    repository {\n      owner {\n        login\n      }\n      name\n      stargazers_count\n    }\n    postedBy {\n      login\n    }\n  }\n}\n"
};

module.exports = batch;
